# Menggunakan Node.js sebagai base image
FROM node:18

# Tentukan direktori kerja di dalam container
WORKDIR /app

# Salin file package.json dan package-lock.json
COPY package*.json ./

# Instal dependencies
RUN npm install

# Salin semua file ke dalam container
COPY . .

# Tetapkan port yang digunakan
ENV PORT 8080

# Jalankan aplikasi
CMD ["npm", "start"]